# Generated by Django 5.2.6 on 2025-11-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='cse', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.CharField(max_length=20),
        ),
    ]
