# Generated by Django 5.2.7 on 2025-10-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10, unique=True)),
                ('student_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
                ('phy', models.IntegerField()),
                ('chem', models.IntegerField()),
                ('math', models.IntegerField()),
            ],
        ),
    ]
