# Generated by Django 5.2.7 on 2025-10-31 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('reg_no', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('EE', 'Electrical Engineering'), ('CE', 'Civil Engineering')], max_length=10)),
                ('year', models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('mobile', models.CharField(max_length=15)),
                ('password', models.CharField(default='student123', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attendance', serialize=False, to='students.student')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_classes', models.IntegerField(default=0)),
                ('classes_attended', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='marks', serialize=False, to='students.student')),
                ('subject1_name', models.CharField(default='Mathematics', max_length=100)),
                ('subject1_ise1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subject1_mid', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subject1_end', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subject2_name', models.CharField(default='Physics', max_length=100)),
                ('subject2_ise1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subject2_mid', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subject2_end', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subject3_name', models.CharField(default='Chemistry', max_length=100)),
                ('subject3_ise1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subject3_mid', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subject3_end', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subject4_name', models.CharField(default='Programming', max_length=100)),
                ('subject4_ise1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subject4_mid', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subject4_end', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subject5_name', models.CharField(default='Data Structures', max_length=100)),
                ('subject5_ise1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subject5_mid', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subject5_end', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
