# Generated by Django 5.2.8 on 2025-11-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=20)),
                ('student_class', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('sub', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('college', models.CharField(max_length=100)),
            ],
        ),
    ]
