# Generated by Django 5.2.6 on 2025-09-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountstudent',
            old_name='cet',
            new_name='fees',
        ),
        migrations.RemoveField(
            model_name='accountstudent',
            name='year',
        ),
        migrations.AddField(
            model_name='accountstudent',
            name='acc_id',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
