# Generated by Django 6.1.1 on 2026-10-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='building',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='section',
            name='time_slot_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='takes',
            name='course_id',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='course_id',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time_slot_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title'], name='course_title_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['dept_name'], name='course_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['building'], name='dept_building_idx'),
        ),
        migrations.AddIndex(
            model_name='instructor',
            index=models.Index(fields=['name'], name='instructor_name_idx'),
        ),
        migrations.AddIndex(
            model_name='instructor',
            index=models.Index(fields=['dept_name'], name='instructor_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['course_id'], name='section_course_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['time_slot_id'], name='section_timeslot_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='student_name_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['dept_name'], name='student_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='takes',
            index=models.Index(fields=['ID'], name='takes_student_idx'),
        ),
        migrations.AddIndex(
            model_name='takes',
            index=models.Index(fields=['course_id'], name='takes_course_idx'),
        ),
        migrations.AddIndex(
            model_name='teaches',
            index=models.Index(fields=['ID'], name='teaches_inst_idx'),
        ),
        migrations.AddIndex(
            model_name='teaches',
            index=models.Index(fields=['course_id'], name='teaches_course_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['time_slot_id'], name='timeslot_id_idx'),
        ),
    ]
