# Generated by Django 5.2.7 on 2025-10-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_faculty_mentor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='regno',
            new_name='roll_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AddField(
            model_name='student',
            name='chemistry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='maths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='physics',
            field=models.IntegerField(default=0),
        ),
    ]
