# Generated by Django 5.2.7 on 2025-10-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_regno_student_roll_no_remove_student_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='chemistry',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='maths',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='physics',
            field=models.FloatField(default=0),
        ),
    ]
