# Generated by Django 5.2.7 on 2025-10-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_cet_student_faculty_mentor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='faculty_mentor',
        ),
    ]
