# Generated by Django 5.2.6 on 2025-09-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=20)),
                ('hostel_name', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=10)),
            ],
        ),
    ]
