# Generated by Django 5.2.6 on 2025-09-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='regno',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
