# Generated by Django 5.2.7 on 2025-10-02 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_student_regno_account_student_and_more'),
        ('library', '0002_alter_library_issued_to'),
        ('student', '0005_student_branch_alter_student_chemistry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='due_amount',
            new_name='due',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='paid_amount',
            new_name='fees_paid',
        ),
        migrations.RemoveField(
            model_name='account',
            name='total_fees',
        ),
        migrations.AddField(
            model_name='account',
            name='branch',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.library'),
        ),
        migrations.AlterField(
            model_name='account',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
