# Generated by Django 5.2.6 on 2025-09-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_no', models.CharField(max_length=20, unique=True, verbose_name='Registration Number')),
                ('year', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=1)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('ENTC', 'Electronics & Telecommunication'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil')], max_length=5)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
            ],
        ),
    ]
