# Generated by Django 5.2.7 on 2025-10-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
