# Generated by Django 5.2.6 on 2025-09-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=20, unique=True)),
                ('hostel_fees', models.DecimalField(decimal_places=2, max_digits=8)),
                ('library_fees', models.DecimalField(decimal_places=2, max_digits=8)),
                ('exam_fees', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
