# Generated by Django 5.2.6 on 2025-11-08 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=20)),
                ('budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=20)),
                ('room_no', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'unique_together': {('building', 'room_no')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('tot_cred', models.IntegerField()),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.department')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.department')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot_id', models.IntegerField()),
                ('day', models.CharField(max_length=10)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
            ],
            options={
                'unique_together': {('time_slot_id', 'day', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portal.student')),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='portal.course')),
                ('prereq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='portal.course')),
            ],
            options={
                'unique_together': {('course_id', 'prereq_id')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_id', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=6)),
                ('year', models.IntegerField()),
                ('building', models.CharField(max_length=20)),
                ('room_no', models.CharField(max_length=20)),
                ('time_slot_id', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.course')),
            ],
            options={
                'unique_together': {('course_id', 'sec_id', 'semester', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('sec_id', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=6)),
                ('year', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.student')),
            ],
            options={
                'unique_together': {('ID', 'course_id', 'sec_id', 'semester', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('sec_id', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=6)),
                ('year', models.IntegerField()),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.instructor')),
            ],
            options={
                'unique_together': {('ID', 'course_id', 'sec_id', 'semester', 'year')},
            },
        ),
    ]
