# Generated by Django 5.2.6 on 2025-09-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelstudent',
            old_name='year',
            new_name='fees',
        ),
        migrations.RemoveField(
            model_name='hostelstudent',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='hostelstudent',
            name='cet',
        ),
        migrations.AddField(
            model_name='hostelstudent',
            name='floor',
            field=models.IntegerField(default=45000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelstudent',
            name='room_no',
            field=models.IntegerField(default=45000),
            preserve_default=False,
        ),
    ]
