# Generated by Django 5.2.8 on 2025-11-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('total_days', models.IntegerField()),
                ('attended_days', models.IntegerField()),
                ('charge_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
