# Generated by Django 5.2.6 on 2025-09-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=20, unique=True)),
                ('fees_type', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
