# Generated by Django 5.2.8 on 2025-11-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=10)),
                ('block', models.CharField(max_length=20)),
                ('floor', models.IntegerField()),
                ('warden_name', models.CharField(max_length=100)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('Occupied', 'Occupied'), ('Vacant', 'Vacant')], max_length=20)),
            ],
        ),
    ]
