# Generated by Django 5.2.6 on 2025-09-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('cet', models.FloatField()),
            ],
        ),
    ]
