# Generated by Django 5.2.7 on 2025-10-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('regno', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('phy', models.IntegerField()),
                ('chem', models.IntegerField()),
                ('math', models.IntegerField()),
            ],
        ),
    ]
