# Generated by Django 5.2.7 on 2025-10-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_designation_faculty_phone_faculty_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='students',
        ),
    ]
