"""
🤖 opencode/llm.py — Multi-LLM Integration (OpenCode)
Supports: OpenAI GPT, Ollama (local), and a built-in fallback analyzer.
"""

import os
import json

# ──────────────────────────────────────────────
# 🧠 Built-in Performance Analyzer (No API needed)
# ──────────────────────────────────────────────
class BuiltInAnalyzer:
    """
    A rule-based analyzer that works WITHOUT any API key.
    Perfect for students who don't have OpenAI credits.
    """

    def generate(self, prompt, student_data=None):
        """Generate a performance report using rules."""
        if not student_data:
            return self._generic_report(prompt)
        return self._detailed_report(student_data)

    def _generic_report(self, prompt):
        return (
            "📊 **Performance Analysis**\n\n"
            "Based on the provided information, here is a general assessment.\n\n"
            "💡 **Tips for Improvement:**\n"
            "• Revise weak subjects regularly\n"
            "• Practice previous year question papers\n"
            "• Maintain consistent study schedule\n"
            "• Focus on understanding concepts, not memorization\n"
        )

    def _detailed_report(self, data):
        """Generate detailed report from structured student data."""
        name = data.get('name', 'Student')
        marks_list = data.get('marks', [])
        branch = data.get('branch', '')
        year = data.get('year', '')

        if not marks_list:
            return f"📊 No marks data available for {name}."

        # Calculate statistics
        totals = [m['total'] for m in marks_list]
        overall_total = sum(totals)
        overall_max = len(marks_list) * 100
        percentage = (overall_total / overall_max * 100) if overall_max > 0 else 0

        # Find strong and weak subjects
        sorted_marks = sorted(marks_list, key=lambda x: x['total'], reverse=True)
        strongest = sorted_marks[0]
        weakest = sorted_marks[-1]

        # Find weak test areas
        weak_tests = []
        for m in marks_list:
            if m['test1'] < 8:  # Less than 40% in test1
                weak_tests.append(f"{m['subject']} (Test 1)")
            if m['test2'] < 8:
                weak_tests.append(f"{m['subject']} (Test 2)")
            if m['final'] < 24:  # Less than 40% in final
                weak_tests.append(f"{m['subject']} (Final Exam)")

        # Grade
        if percentage >= 90:
            grade_remark = "🏆 Outstanding! You are a top performer!"
            emoji = "🌟"
        elif percentage >= 80:
            grade_remark = "🎯 Excellent work! Keep pushing for the top!"
            emoji = "✨"
        elif percentage >= 70:
            grade_remark = "👍 Very good performance. Small improvements can take you higher."
            emoji = "💪"
        elif percentage >= 60:
            grade_remark = "📈 Good effort. Focus on consistency across all subjects."
            emoji = "📚"
        elif percentage >= 50:
            grade_remark = "⚠️ Average performance. Needs more dedicated study time."
            emoji = "📖"
        elif percentage >= 40:
            grade_remark = "🔶 Just passing. Serious improvement needed in weak areas."
            emoji = "⚡"
        else:
            grade_remark = "🔴 Below passing. Immediate action required — seek help from teachers."
            emoji = "🚨"

        # Build report
        report = f"""
{emoji} **Performance Analysis for {name}**
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎓 **Branch:** {branch}
📅 **Year:** {year}

📊 **Overall Score:** {overall_total} / {overall_max} ({percentage:.1f}%)

{grade_remark}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📗 **Strongest Subject:** {strongest['subject']} ({strongest['total']}/100)
📕 **Weakest Subject:** {weakest['subject']} ({weakest['total']}/100)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📋 **Subject-wise Breakdown:**
"""
        for m in marks_list:
            bar_len = int(m['total'] / 5)  # Scale to ~20 chars
            bar = "█" * bar_len + "░" * (20 - bar_len)
            status = "✅" if m['total'] >= 40 else "❌"
            report += f"  {status} {m['subject']}: {m['total']}/100  [{bar}]\n"

        report += "\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"

        if weak_tests:
            report += "\n⚠️ **Areas Needing Attention:**\n"
            for wt in weak_tests:
                report += f"  • {wt}\n"

        report += """
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💡 **Improvement Tips:**
  1. 📖 Revise weak subjects daily for 30 minutes
  2. 📝 Solve previous year papers for exam practice
  3. 👥 Form study groups for difficult topics
  4. 🎯 Set small goals for each test
  5. 🧘 Take breaks — a fresh mind learns better!

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🤖 Report generated by Built-in Analyzer (no API required)
"""
        return report


# ──────────────────────────────────────────────
# 🌐 OpenAI GPT Integration
# ──────────────────────────────────────────────
class OpenAIProvider:
    """Uses OpenAI GPT models for analysis."""

    def __init__(self):
        try:
            from openai import OpenAI
            api_key = os.getenv("OPENAI_API_KEY", "")
            if api_key:
                self.client = OpenAI(api_key=api_key)
                self.available = True
            else:
                self.client = None
                self.available = False
        except ImportError:
            self.client = None
            self.available = False

    def generate(self, prompt):
        if not self.available:
            return None
        try:
            response = self.client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}]
            )
            return response.choices[0].message.content
        except Exception as e:
            return f"⚠️ OpenAI Error: {str(e)}"


# ──────────────────────────────────────────────
# 🦙 Ollama (Local LLM) Integration
# ──────────────────────────────────────────────
class OllamaProvider:
    """Uses locally running Ollama models."""

    def __init__(self):
        self.base_url = os.getenv("OLLAMA_URL", "http://localhost:11434")
        self.model = os.getenv("OLLAMA_MODEL", "llama3")
        self.available = self._check_available()

    def _check_available(self):
        try:
            import urllib.request
            req = urllib.request.Request(f"{self.base_url}/api/tags")
            urllib.request.urlopen(req, timeout=2)
            return True
        except Exception:
            return False

    def generate(self, prompt):
        if not self.available:
            return None
        try:
            import urllib.request
            data = json.dumps({
                "model": self.model,
                "prompt": prompt,
                "stream": False
            }).encode()
            req = urllib.request.Request(
                f"{self.base_url}/api/generate",
                data=data,
                headers={"Content-Type": "application/json"}
            )
            response = urllib.request.urlopen(req, timeout=30)
            result = json.loads(response.read())
            return result.get("response", "No response from Ollama.")
        except Exception as e:
            return f"⚠️ Ollama Error: {str(e)}"


# ──────────────────────────────────────────────
# 🤖 Main OpenCode LLM Class (Multi-Provider)
# ──────────────────────────────────────────────
class OpenCodeLLM:
    """
    Multi-model LLM integration.
    Falls back gracefully: OpenAI → Ollama → Built-in Analyzer
    """

    def __init__(self):
        self.builtin = BuiltInAnalyzer()
        self.openai = OpenAIProvider()
        self.ollama = OllamaProvider()

    def get_available_providers(self):
        """Return list of available providers."""
        providers = ['builtin']  # Always available
        if self.openai.available:
            providers.append('openai')
        if self.ollama.available:
            providers.append('ollama')
        return providers

    def generate(self, prompt, provider="auto", student_data=None):
        """
        Generate AI report using specified provider.
        provider: 'auto', 'openai', 'ollama', 'builtin'
        """
        if provider == "auto":
            # Try OpenAI first, then Ollama, then built-in
            if self.openai.available:
                result = self.openai.generate(prompt)
                if result:
                    return result, "openai"

            if self.ollama.available:
                result = self.ollama.generate(prompt)
                if result:
                    return result, "ollama"

            return self.builtin.generate(prompt, student_data), "builtin"

        elif provider == "openai":
            if self.openai.available:
                result = self.openai.generate(prompt)
                return result or "OpenAI unavailable.", "openai"
            return "⚠️ OpenAI API key not configured.", "openai"

        elif provider == "ollama":
            if self.ollama.available:
                result = self.ollama.generate(prompt)
                return result or "Ollama unavailable.", "ollama"
            return "⚠️ Ollama is not running locally.", "ollama"

        else:
            return self.builtin.generate(prompt, student_data), "builtin"

    def generate_comparison(self, prompt, student_data=None):
        """Generate reports from ALL available providers for comparison."""
        results = {}

        # Built-in (always available)
        results['builtin'] = self.builtin.generate(prompt, student_data)

        # OpenAI
        if self.openai.available:
            results['openai'] = self.openai.generate(prompt)

        # Ollama
        if self.ollama.available:
            results['ollama'] = self.ollama.generate(prompt)

        return results
